package com.skillstorm.beans;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="Artist")
public class Artist {
	
	@Id // Primary Key
	@Column(name="ArtistId") // use the java property as the database column name
	@GeneratedValue(strategy = GenerationType.IDENTITY) // PK is generated by the database
	private int Id;
	private String name;
	public Artist() {
		super();
	}
	public Artist(String name) {
		super();
		this.name = name;
	}
	public Artist(int Id, String name) {
		super();
		this.Id = Id;
		this.name = name;
	}
	public int getId() {
		return Id;
	}
	public void setId(int Id) {
		this.Id = Id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@Override
	public String toString() {
		return "Artist [Id=" + Id + ", name=" + name + "]";
	}
	
	
	
}
